import { db } from "./firebase";
import { collection, addDoc, getDocs, query, where, updateDoc, doc } from "firebase/firestore";
import { SystemTicket } from "../types";

export async function createAutoTicket(data: {
  patientName: string;
  nationalId: string;
  phone?: string;
  department?: string;
  visitReason?: string;
  priority?: "Normal" | "Urgent" | "Emergency";
  patientId?: string;
}): Promise<string | null> {
  try {
    if (!data.patientName || !data.nationalId) return null;

    const ticketNo = `TCK-${Math.floor(1000 + Math.random() * 9000)}`;
    const newTicket: Omit<SystemTicket, "id"> = {
      ticketNumber: ticketNo,
      patientId: data.patientId || "",
      patientName: data.patientName,
      nationalId: data.nationalId,
      phone: data.phone || "",
      visitReason: data.visitReason || "Outpatient Clinical Intake & Consultation",
      department: data.department || "reception",
      priority: data.priority || "Normal",
      status: "open",
      createdTime: new Date().toLocaleString("en-KE", { dateStyle: "short", timeStyle: "medium" }),
      autoGenerated: true
    };

    const docRef = await addDoc(collection(db, "system_tickets"), newTicket);
    console.log(`Auto ticket created [${ticketNo}] for ${data.patientName}`);
    return docRef.id;
  } catch (err) {
    console.error("Error creating auto ticket:", err);
    return null;
  }
}

export async function closeAutoTicket(patientIdentifier: string, resolutionNotes?: string): Promise<boolean> {
  try {
    if (!patientIdentifier) return false;

    // Search by nationalId or patientName
    const q1 = query(
      collection(db, "system_tickets"), 
      where("nationalId", "==", patientIdentifier),
      where("status", "in", ["open", "in_progress"])
    );
    let snap = await getDocs(q1);

    if (snap.empty) {
      const q2 = query(
        collection(db, "system_tickets"),
        where("patientName", "==", patientIdentifier),
        where("status", "in", ["open", "in_progress"])
      );
      snap = await getDocs(q2);
    }

    if (snap.empty) {
      console.log(`No open ticket found for ${patientIdentifier} to close.`);
      return false;
    }

    const closedTimeStr = new Date().toLocaleString("en-KE", { dateStyle: "short", timeStyle: "medium" });

    for (const ticketDoc of snap.docs) {
      await updateDoc(doc(db, "system_tickets", ticketDoc.id), {
        status: "closed",
        closedTime: closedTimeStr,
        closedBy: "System Checkout Auto-Trigger",
        resolutionNotes: resolutionNotes || "Patient completed hospital intake, clinical services, and billing checkout."
      });
      console.log(`Ticket [${ticketDoc.data().ticketNumber}] automatically closed on checkout.`);
    }

    return true;
  } catch (err) {
    console.error("Error closing ticket for patient:", err);
    return false;
  }
}

export async function closeAutoTicketById(ticketId: string, resolutionNotes?: string, closedBy?: string): Promise<boolean> {
  try {
    const closedTimeStr = new Date().toLocaleString("en-KE", { dateStyle: "short", timeStyle: "medium" });
    await updateDoc(doc(db, "system_tickets", ticketId), {
      status: "closed",
      closedTime: closedTimeStr,
      closedBy: closedBy || "Hospital Staff",
      resolutionNotes: resolutionNotes || "Ticket resolved and patient encounter completed."
    });
    return true;
  } catch (err) {
    console.error("Error closing ticket by id:", err);
    return false;
  }
}
