import React, { useState, useEffect } from "react";
import { db } from "../lib/firebase";
import { collection, onSnapshot, addDoc, updateDoc, doc, deleteDoc } from "firebase/firestore";
import { SystemTicket } from "../types";
import { closeAutoTicketById } from "../lib/ticketService";
import { 
  Ticket, 
  CheckCircle2, 
  Clock, 
  AlertCircle, 
  Search, 
  Filter, 
  Plus, 
  User, 
  Phone, 
  Building2, 
  Sparkles, 
  ShieldCheck, 
  X, 
  MessageSquare, 
  Activity,
  ArrowRight,
  Check,
  CheckSquare
} from "lucide-react";

export default function TicketSystem() {
  const [tickets, setTickets] = useState<SystemTicket[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<"all" | "open" | "in_progress" | "closed">("all");
  const [priorityFilter, setPriorityFilter] = useState<string>("all");
  const [typeFilter, setTypeFilter] = useState<"all" | "auto" | "manual">("all");

  // New Ticket Modal State
  const [showModal, setShowModal] = useState(false);
  const [patientName, setPatientName] = useState("");
  const [nationalId, setNationalId] = useState("");
  const [phone, setPhone] = useState("");
  const [department, setDepartment] = useState("reception");
  const [visitReason, setVisitReason] = useState("Outpatient Clinical Consultation");
  const [priority, setPriority] = useState<"Normal" | "Urgent" | "Emergency">("Normal");

  // Close Resolution Modal State
  const [resolvingTicket, setResolvingTicket] = useState<SystemTicket | null>(null);
  const [resolutionNotes, setResolutionNotes] = useState("");

  useEffect(() => {
    const unsub = onSnapshot(collection(db, "system_tickets"), (snapshot) => {
      const docs: SystemTicket[] = [];
      snapshot.forEach((d) => {
        docs.push({ id: d.id, ...d.data() } as SystemTicket);
      });
      // Sort newest first
      docs.sort((a, b) => new Date(b.createdTime).getTime() - new Date(a.createdTime).getTime());
      setTickets(docs);

      // Seed sample tickets if empty
      if (snapshot.empty) {
        seedInitialTickets();
      }
    });

    return () => unsub();
  }, []);

  const seedInitialTickets = async () => {
    const initial: Omit<SystemTicket, "id">[] = [
      {
        ticketNumber: "TCK-4819",
        patientName: "Alice Wambui Kamau",
        nationalId: "32441928",
        phone: "0711943210",
        visitReason: "Acute Fever & SHA Eligibility Verification",
        department: "doctor",
        priority: "Normal",
        status: "open",
        createdTime: new Date(Date.now() - 45 * 60000).toLocaleString("en-KE"),
        autoGenerated: true,
      },
      {
        ticketNumber: "TCK-9021",
        patientName: "David Omondi Otieno",
        nationalId: "29110482",
        phone: "0722004481",
        visitReason: "Hypertension Follow-Up & Lab Lipid Test",
        department: "laboratory",
        priority: "Urgent",
        status: "in_progress",
        createdTime: new Date(Date.now() - 120 * 60000).toLocaleString("en-KE"),
        autoGenerated: true,
      },
      {
        ticketNumber: "TCK-1104",
        patientName: "Mary Muthoni Njoroge",
        nationalId: "35109822",
        phone: "0788123901",
        visitReason: "Pediatric Emergency Immunization",
        department: "billing",
        priority: "Emergency",
        status: "closed",
        createdTime: new Date(Date.now() - 360 * 60000).toLocaleString("en-KE"),
        closedTime: new Date(Date.now() - 60 * 60000).toLocaleString("en-KE"),
        closedBy: "Paperless Billing Checkout",
        resolutionNotes: "Invoice paid via M-PESA. Patient checked out successfully.",
        autoGenerated: true,
      }
    ];

    for (const t of initial) {
      await addDoc(collection(db, "system_tickets"), t);
    }
  };

  const handleCreateTicket = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!patientName || !nationalId) return;

    try {
      const tckNo = `TCK-${Math.floor(1000 + Math.random() * 9000)}`;
      await addDoc(collection(db, "system_tickets"), {
        ticketNumber: tckNo,
        patientName,
        nationalId,
        phone,
        department,
        visitReason,
        priority,
        status: "open",
        createdTime: new Date().toLocaleString("en-KE"),
        autoGenerated: false,
      });

      setShowModal(false);
      setPatientName("");
      setNationalId("");
      setPhone("");
      setVisitReason("Outpatient Clinical Consultation");
    } catch (err) {
      console.error("Error creating ticket:", err);
    }
  };

  const handleConfirmCloseTicket = async () => {
    if (!resolvingTicket) return;
    await closeAutoTicketById(resolvingTicket.id, resolutionNotes, "Staff Manual Action");
    setResolvingTicket(null);
    setResolutionNotes("");
  };

  const filteredTickets = tickets.filter((t) => {
    const matchesSearch = 
      t.ticketNumber?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.patientName?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      t.nationalId?.includes(searchQuery) ||
      t.visitReason?.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesStatus = statusFilter === "all" || t.status === statusFilter;
    const matchesPriority = priorityFilter === "all" || t.priority === priorityFilter;
    const matchesType = 
      typeFilter === "all" || 
      (typeFilter === "auto" && t.autoGenerated) || 
      (typeFilter === "manual" && !t.autoGenerated);

    return matchesSearch && matchesStatus && matchesPriority && matchesType;
  });

  const openCount = tickets.filter(t => t.status === "open" || t.status === "in_progress").length;
  const closedCount = tickets.filter(t => t.status === "closed").length;
  const autoCount = tickets.filter(t => t.autoGenerated).length;
  const emergencyCount = tickets.filter(t => t.priority === "Emergency" && t.status !== "closed").length;

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto animate-fade-in">
      
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-indigo-950 text-white p-6 rounded-2xl shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4 border border-slate-700">
        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="p-2 bg-emerald-500/20 text-emerald-400 rounded-xl border border-emerald-500/30">
              <Ticket className="w-6 h-6 animate-pulse" />
            </span>
            <h1 className="text-2xl font-bold tracking-tight uppercase font-comfortaa">Automated Client Ticket System</h1>
          </div>
          <p className="text-xs text-slate-300 max-w-2xl leading-relaxed">
            Every client keyed into the hospital system automatically triggers an encounter ticket. Tickets automatically transition through triage, consultation, diagnostics, and auto-close upon client checkout.
          </p>
        </div>

        <button
          onClick={() => setShowModal(true)}
          className="px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl text-xs uppercase tracking-wider transition-all duration-200 shadow-lg shadow-emerald-950/40 flex items-center gap-2 cursor-pointer shrink-0"
        >
          <Plus className="w-4 h-4" />
          <span>New Manual Ticket</span>
        </button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Active Open Tickets</p>
            <p className="text-2xl font-black text-amber-600 font-mono mt-0.5">{openCount}</p>
          </div>
          <div className="p-3 bg-amber-50 text-amber-600 rounded-xl">
            <Clock className="w-5 h-5 animate-spin" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Closed on Checkout</p>
            <p className="text-2xl font-black text-emerald-600 font-mono mt-0.5">{closedCount}</p>
          </div>
          <div className="p-3 bg-emerald-50 text-emerald-600 rounded-xl">
            <CheckCircle2 className="w-5 h-5" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Auto-Intake Tickets</p>
            <p className="text-2xl font-black text-indigo-600 font-mono mt-0.5">{autoCount}</p>
          </div>
          <div className="p-3 bg-indigo-50 text-indigo-600 rounded-xl">
            <Sparkles className="w-5 h-5" />
          </div>
        </div>

        <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm flex items-center justify-between">
          <div>
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Emergency Tickets</p>
            <p className="text-2xl font-black text-rose-600 font-mono mt-0.5">{emergencyCount}</p>
          </div>
          <div className="p-3 bg-rose-50 text-rose-600 rounded-xl">
            <AlertCircle className="w-5 h-5" />
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-4 rounded-2xl border border-gray-200 shadow-sm space-y-3">
        <div className="flex flex-col md:flex-row items-stretch md:items-center gap-3">
          <div className="relative flex-grow">
            <Search className="w-4 h-4 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search by Ticket No, Patient Name, National ID, or Complaint..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-semibold text-gray-800 focus:outline-emerald-500"
            />
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value as any)}
              className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-bold text-gray-700 cursor-pointer"
            >
              <option value="all">All Statuses</option>
              <option value="open">Open / Pending</option>
              <option value="in_progress">In Progress</option>
              <option value="closed">Closed on Checkout</option>
            </select>

            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value)}
              className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-bold text-gray-700 cursor-pointer"
            >
              <option value="all">All Priorities</option>
              <option value="Normal">Normal</option>
              <option value="Urgent">Urgent</option>
              <option value="Emergency">Emergency</option>
            </select>

            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value as any)}
              className="px-3 py-2 bg-gray-50 border border-gray-200 rounded-xl text-xs font-bold text-gray-700 cursor-pointer"
            >
              <option value="all">All Types</option>
              <option value="auto">Auto-Generated</option>
              <option value="manual">Manual Staff</option>
            </select>
          </div>
        </div>
      </div>

      {/* Tickets List / Table */}
      <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-gray-200 bg-gray-50/50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Ticket className="w-4 h-4 text-emerald-600" />
            <h2 className="text-xs font-bold text-gray-800 uppercase tracking-wider">Hospital Client Tickets ({filteredTickets.length})</h2>
          </div>
          <span className="text-[10px] font-bold text-gray-400 font-mono">Real-Time Sync Active</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="bg-gray-100/70 text-gray-500 font-bold uppercase text-[9px] tracking-wider border-b border-gray-200">
                <th className="py-3 px-4">Ticket No</th>
                <th className="py-3 px-4">Client / Patient</th>
                <th className="py-3 px-4">Visit Reason / Issue</th>
                <th className="py-3 px-4">Department</th>
                <th className="py-3 px-4">Priority</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Intake Time</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 text-gray-700">
              {filteredTickets.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-8 text-center text-gray-400 font-medium">
                    No tickets found matching your filter criteria.
                  </td>
                </tr>
              ) : (
                filteredTickets.map((ticket) => (
                  <tr key={ticket.id} className="hover:bg-gray-50/80 transition-colors">
                    <td className="py-3.5 px-4 font-mono font-bold text-slate-900">
                      <div className="flex items-center gap-1.5">
                        <span>{ticket.ticketNumber}</span>
                        {ticket.autoGenerated && (
                          <span className="px-1.5 py-0.2 bg-indigo-50 text-indigo-600 border border-indigo-200 rounded text-[8px] font-extrabold uppercase">AUTO</span>
                        )}
                      </div>
                    </td>

                    <td className="py-3.5 px-4">
                      <div className="font-bold text-gray-900">{ticket.patientName}</div>
                      <div className="text-[10px] text-gray-400 font-mono">ID: {ticket.nationalId} {ticket.phone ? `• ${ticket.phone}` : ""}</div>
                    </td>

                    <td className="py-3.5 px-4 max-w-xs">
                      <p className="font-semibold text-gray-800 truncate" title={ticket.visitReason}>{ticket.visitReason}</p>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className="px-2 py-0.5 bg-slate-100 text-slate-700 font-bold rounded-lg text-[10px] uppercase">
                        {ticket.department}
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      <span className={`px-2 py-0.5 rounded-lg text-[10px] font-black uppercase ${
                        ticket.priority === "Emergency"
                          ? "bg-rose-100 text-rose-700 border border-rose-200 animate-pulse"
                          : ticket.priority === "Urgent"
                          ? "bg-amber-100 text-amber-700 border border-amber-200"
                          : "bg-gray-100 text-gray-700"
                      }`}>
                        {ticket.priority}
                      </span>
                    </td>

                    <td className="py-3.5 px-4">
                      {ticket.status === "closed" ? (
                        <div className="space-y-0.5">
                          <span className="px-2 py-0.5 bg-emerald-100 text-emerald-800 rounded-lg text-[10px] font-bold inline-flex items-center gap-1">
                            <CheckCircle2 className="w-3 h-3 text-emerald-600" /> Closed
                          </span>
                          {ticket.closedTime && <p className="text-[9px] text-gray-400 font-mono">{ticket.closedTime}</p>}
                        </div>
                      ) : ticket.status === "in_progress" ? (
                        <span className="px-2 py-0.5 bg-blue-100 text-blue-800 rounded-lg text-[10px] font-bold inline-flex items-center gap-1">
                          <Activity className="w-3 h-3 text-blue-600 animate-spin" /> In Progress
                        </span>
                      ) : (
                        <span className="px-2 py-0.5 bg-amber-100 text-amber-800 rounded-lg text-[10px] font-bold inline-flex items-center gap-1">
                          <Clock className="w-3 h-3 text-amber-600 animate-pulse" /> Open Intake
                        </span>
                      )}
                    </td>

                    <td className="py-3.5 px-4 text-[10px] font-mono text-gray-500">
                      {ticket.createdTime}
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      {ticket.status !== "closed" ? (
                        <button
                          onClick={() => setResolvingTicket(ticket)}
                          className="px-2.5 py-1 bg-emerald-600 hover:bg-emerald-500 text-white text-[10px] font-bold rounded-lg uppercase tracking-wider transition-all cursor-pointer shadow-xs inline-flex items-center gap-1"
                        >
                          <Check className="w-3 h-3" /> Close Ticket
                        </button>
                      ) : (
                        <span className="text-[10px] font-bold text-gray-400 italic">Resolved</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Manual Ticket Creation Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-white w-full max-w-lg rounded-2xl shadow-2xl border border-gray-200 overflow-hidden animate-scale-up">
            <div className="p-4 bg-slate-900 text-white flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Ticket className="w-5 h-5 text-emerald-400" />
                <h3 className="font-bold text-sm uppercase">Create Manual Client Ticket</h3>
              </div>
              <button onClick={() => setShowModal(false)} className="text-slate-400 hover:text-white cursor-pointer">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateTicket} className="p-5 space-y-4">
              <div className="space-y-1">
                <label className="block text-xs font-bold text-gray-700">Client / Patient Full Name *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Samuel Mutua"
                  value={patientName}
                  onChange={(e) => setPatientName(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-semibold focus:outline-emerald-500"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="block text-xs font-bold text-gray-700">National ID / Passport *</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. 28910482"
                    value={nationalId}
                    onChange={(e) => setNationalId(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-semibold focus:outline-emerald-500 font-mono"
                  />
                </div>

                <div className="space-y-1">
                  <label className="block text-xs font-bold text-gray-700">Phone Number</label>
                  <input
                    type="text"
                    placeholder="e.g. 0712345678"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-semibold focus:outline-emerald-500 font-mono"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="block text-xs font-bold text-gray-700">Department</label>
                  <select
                    value={department}
                    onChange={(e) => setDepartment(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-bold text-gray-800"
                  >
                    <option value="reception">Reception Intake</option>
                    <option value="doctor">Doctor Consultation</option>
                    <option value="laboratory">Laboratory</option>
                    <option value="radiology">Radiology</option>
                    <option value="pharmacy">Pharmacy</option>
                    <option value="billing">Billing & Finance</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="block text-xs font-bold text-gray-700">Priority Level</label>
                  <select
                    value={priority}
                    onChange={(e) => setPriority(e.target.value as any)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-bold text-gray-800"
                  >
                    <option value="Normal">Normal</option>
                    <option value="Urgent">Urgent</option>
                    <option value="Emergency">Emergency</option>
                  </select>
                </div>
              </div>

              <div className="space-y-1">
                <label className="block text-xs font-bold text-gray-700">Visit Reason / Clinical Issue</label>
                <textarea
                  rows={2}
                  placeholder="Describe client symptoms or intake purpose..."
                  value={visitReason}
                  onChange={(e) => setVisitReason(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs font-medium focus:outline-emerald-500"
                ></textarea>
              </div>

              <div className="pt-2 flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowModal(false)}
                  className="px-4 py-2 bg-gray-100 text-gray-700 font-bold rounded-xl text-xs cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl text-xs uppercase cursor-pointer shadow-md"
                >
                  Create Ticket
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Close Ticket Confirmation Modal */}
      {resolvingTicket && (
        <div className="fixed inset-0 bg-slate-950/70 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-white w-full max-w-md rounded-2xl shadow-2xl border border-gray-200 p-5 space-y-4">
            <div className="flex items-center gap-2 text-emerald-600">
              <CheckSquare className="w-5 h-5" />
              <h3 className="font-bold text-sm uppercase">Close Ticket: {resolvingTicket.ticketNumber}</h3>
            </div>

            <p className="text-xs text-gray-600">
              Closing ticket for <strong className="text-gray-900">{resolvingTicket.patientName}</strong> (ID: {resolvingTicket.nationalId}).
            </p>

            <div className="space-y-1">
              <label className="block text-xs font-bold text-gray-700">Resolution / Checkout Notes</label>
              <textarea
                rows={3}
                placeholder="Enter completion details or checkout notes..."
                value={resolutionNotes}
                onChange={(e) => setResolutionNotes(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-xl text-xs focus:outline-emerald-500"
              ></textarea>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                onClick={() => setResolvingTicket(null)}
                className="px-4 py-2 bg-gray-100 text-gray-700 font-bold rounded-xl text-xs cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleConfirmCloseTicket}
                className="px-5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl text-xs uppercase cursor-pointer shadow-md"
              >
                Confirm Close
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
